# It's OK to disable this CI check if it's causing problems because the
# JetBrains client team can manually update and maintain the bindings
# until we fix the automation. This automation should NOT be blocking
# you from making progress on critical work.
# Please post in #wg-cody-agent to share feedback about this CI check.
name: agent-bindings (disable if causing problems)
on:
  pull_request:
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.js'

jobs:
  kotlin:
    if: github.repository == 'sourcegraph/cody'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # SECURITY: pin third-party action hashes
        id: pnpm-install
        with:
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm install --frozen-lockfile
      - run: ./agent/scripts/generate-agent-kotlin-bindings.sh
      - run: ./agent/scripts/error-if-diff.sh
      - run: ./agent/scripts/compile-bindings-if-diff.sh
