# Please post in #team-cody-clients if you need help getting this CI check to pass.
# Worst-case: feel free to disable this workflow here https://github.com/sourcegraph/cody/actions/workflows/agent-bindings.yml
name: agent-bindings
on:

  pull_request:
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.js'

jobs:
  kotlin:
    if: github.repository == 'sourcegraph/cody'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # SECURITY: pin third-party action hashes
        id: pnpm-install
        with:
          version: 8.6.7
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm install --frozen-lockfile
      - run: pnpm generate-agent-kotlin-bindings
      - run: ./agent/scripts/error-if-diff.sh
      - run: ./agent/scripts/compile-bindings-if-diff.sh
